package com.heyzeusv.solitaire

object TestCards {

    val card0D = Card(0, Suits.DIAMONDS)
    val card1D = Card(1, Suits.DIAMONDS)
    val card2D = Card(2, Suits.DIAMONDS)
    val card3D = Card(3, Suits.DIAMONDS)
    val card4D = Card(4, Suits.DIAMONDS)
    val card5D = Card(5, Suits.DIAMONDS)
    val card6D = Card(6, Suits.DIAMONDS)
    val card7D = Card(7, Suits.DIAMONDS)
    val card8D = Card(8, Suits.DIAMONDS)
    val card9D = Card(9, Suits.DIAMONDS)
    val card10D = Card(10, Suits.DIAMONDS)
    val card11D = Card(11, Suits.DIAMONDS)
    val card12D = Card(12, Suits.DIAMONDS)

    val card0C = Card(0, Suits.CLUBS)
    val card1C = Card(1, Suits.CLUBS)
    val card2C = Card(2, Suits.CLUBS)
    val card3C = Card(3, Suits.CLUBS)
    val card4C = Card(4, Suits.CLUBS)
    val card5C = Card(5, Suits.CLUBS)
    val card6C = Card(6, Suits.CLUBS)
    val card7C = Card(7, Suits.CLUBS)
    val card8C = Card(8, Suits.CLUBS)
    val card9C = Card(9, Suits.CLUBS)
    val card10C = Card(10, Suits.CLUBS)
    val card11C = Card(11, Suits.CLUBS)
    val card12C = Card(12, Suits.CLUBS)

    val card0S = Card(0, Suits.SPADES)
    val card1S = Card(1, Suits.SPADES)
    val card2S = Card(2, Suits.SPADES)
    val card3S = Card(3, Suits.SPADES)
    val card4S = Card(4, Suits.SPADES)
    val card5S = Card(5, Suits.SPADES)
    val card6S = Card(6, Suits.SPADES)
    val card7S = Card(7, Suits.SPADES)
    val card8S = Card(8, Suits.SPADES)
    val card9S = Card(9, Suits.SPADES)
    val card10S = Card(10, Suits.SPADES)
    val card11S = Card(11, Suits.SPADES)
    val card12S = Card(12, Suits.SPADES)

    val card0H = Card(0, Suits.HEARTS)
    val card1H = Card(1, Suits.HEARTS)
    val card2H = Card(2, Suits.HEARTS)
    val card3H = Card(3, Suits.HEARTS)
    val card4H = Card(4, Suits.HEARTS)
    val card5H = Card(5, Suits.HEARTS)
    val card6H = Card(6, Suits.HEARTS)
    val card7H = Card(7, Suits.HEARTS)
    val card8H = Card(8, Suits.HEARTS)
    val card9H = Card(9, Suits.HEARTS)
    val card10H = Card(10, Suits.HEARTS)
    val card11H = Card(11, Suits.HEARTS)
    val card12H = Card(12, Suits.HEARTS)
}