package com.heyzeusv.solitaire.util

import com.heyzeusv.solitaire.board.piles.Card

@Suppress("MemberVisibilityCanBePrivate", "unused")
object TestCards {

    val card1C = Card(0, Suits.CLUBS)
    val card2C = Card(1, Suits.CLUBS)
    val card3C = Card(2, Suits.CLUBS)
    val card4C = Card(3, Suits.CLUBS)
    val card5C = Card(4, Suits.CLUBS)
    val card6C = Card(5, Suits.CLUBS)
    val card7C = Card(6, Suits.CLUBS)
    val card8C = Card(7, Suits.CLUBS)
    val card9C = Card(8, Suits.CLUBS)
    val card10C = Card(9, Suits.CLUBS)
    val card11C = Card(10, Suits.CLUBS)
    val card12C = Card(11, Suits.CLUBS)
    val card13C = Card(12, Suits.CLUBS)

    val card1D = Card(0, Suits.DIAMONDS)
    val card2D = Card(1, Suits.DIAMONDS)
    val card3D = Card(2, Suits.DIAMONDS)
    val card4D = Card(3, Suits.DIAMONDS)
    val card5D = Card(4, Suits.DIAMONDS)
    val card6D = Card(5, Suits.DIAMONDS)
    val card7D = Card(6, Suits.DIAMONDS)
    val card8D = Card(7, Suits.DIAMONDS)
    val card9D = Card(8, Suits.DIAMONDS)
    val card10D = Card(9, Suits.DIAMONDS)
    val card11D = Card(10, Suits.DIAMONDS)
    val card12D = Card(11, Suits.DIAMONDS)
    val card13D = Card(12, Suits.DIAMONDS)

    val card1H = Card(0, Suits.HEARTS)
    val card2H = Card(1, Suits.HEARTS)
    val card3H = Card(2, Suits.HEARTS)
    val card4H = Card(3, Suits.HEARTS)
    val card5H = Card(4, Suits.HEARTS)
    val card6H = Card(5, Suits.HEARTS)
    val card7H = Card(6, Suits.HEARTS)
    val card8H = Card(7, Suits.HEARTS)
    val card9H = Card(8, Suits.HEARTS)
    val card10H = Card(9, Suits.HEARTS)
    val card11H = Card(10, Suits.HEARTS)
    val card12H = Card(11, Suits.HEARTS)
    val card13H = Card(12, Suits.HEARTS)

    val card1S = Card(0, Suits.SPADES)
    val card2S = Card(1, Suits.SPADES)
    val card3S = Card(2, Suits.SPADES)
    val card4S = Card(3, Suits.SPADES)
    val card5S = Card(4, Suits.SPADES)
    val card6S = Card(5, Suits.SPADES)
    val card7S = Card(6, Suits.SPADES)
    val card8S = Card(7, Suits.SPADES)
    val card9S = Card(8, Suits.SPADES)
    val card10S = Card(9, Suits.SPADES)
    val card11S = Card(10, Suits.SPADES)
    val card12S = Card(11, Suits.SPADES)
    val card13S = Card(12, Suits.SPADES)

    val card1CFU = Card(0, Suits.CLUBS, faceUp = true)
    val card2CFU = Card(1, Suits.CLUBS, faceUp = true)
    val card3CFU = Card(2, Suits.CLUBS, faceUp = true)
    val card4CFU = Card(3, Suits.CLUBS, faceUp = true)
    val card5CFU = Card(4, Suits.CLUBS, faceUp = true)
    val card6CFU = Card(5, Suits.CLUBS, faceUp = true)
    val card7CFU = Card(6, Suits.CLUBS, faceUp = true)
    val card8CFU = Card(7, Suits.CLUBS, faceUp = true)
    val card9CFU = Card(8, Suits.CLUBS, faceUp = true)
    val card10CFU = Card(9, Suits.CLUBS, faceUp = true)
    val card11CFU = Card(10, Suits.CLUBS, faceUp = true)
    val card12CFU = Card(11, Suits.CLUBS, faceUp = true)
    val card13CFU = Card(12, Suits.CLUBS, faceUp = true)

    val card1DFU = Card(0, Suits.DIAMONDS, faceUp = true)
    val card2DFU = Card(1, Suits.DIAMONDS, faceUp = true)
    val card3DFU = Card(2, Suits.DIAMONDS, faceUp = true)
    val card4DFU = Card(3, Suits.DIAMONDS, faceUp = true)
    val card5DFU = Card(4, Suits.DIAMONDS, faceUp = true)
    val card6DFU = Card(5, Suits.DIAMONDS, faceUp = true)
    val card7DFU = Card(6, Suits.DIAMONDS, faceUp = true)
    val card8DFU = Card(7, Suits.DIAMONDS, faceUp = true)
    val card9DFU = Card(8, Suits.DIAMONDS, faceUp = true)
    val card10DFU = Card(9, Suits.DIAMONDS, faceUp = true)
    val card11DFU = Card(10, Suits.DIAMONDS, faceUp = true)
    val card12DFU = Card(11, Suits.DIAMONDS, faceUp = true)
    val card13DFU = Card(12, Suits.DIAMONDS, faceUp = true)

    val card1HFU = Card(0, Suits.HEARTS, faceUp = true)
    val card2HFU = Card(1, Suits.HEARTS, faceUp = true)
    val card3HFU = Card(2, Suits.HEARTS, faceUp = true)
    val card4HFU = Card(3, Suits.HEARTS, faceUp = true)
    val card5HFU = Card(4, Suits.HEARTS, faceUp = true)
    val card6HFU = Card(5, Suits.HEARTS, faceUp = true)
    val card7HFU = Card(6, Suits.HEARTS, faceUp = true)
    val card8HFU = Card(7, Suits.HEARTS, faceUp = true)
    val card9HFU = Card(8, Suits.HEARTS, faceUp = true)
    val card10HFU = Card(9, Suits.HEARTS, faceUp = true)
    val card11HFU = Card(10, Suits.HEARTS, faceUp = true)
    val card12HFU = Card(11, Suits.HEARTS, faceUp = true)
    val card13HFU = Card(12, Suits.HEARTS, faceUp = true)

    val card1SFU = Card(0, Suits.SPADES, faceUp = true)
    val card2SFU = Card(1, Suits.SPADES, faceUp = true)
    val card3SFU = Card(2, Suits.SPADES, faceUp = true)
    val card4SFU = Card(3, Suits.SPADES, faceUp = true)
    val card5SFU = Card(4, Suits.SPADES, faceUp = true)
    val card6SFU = Card(5, Suits.SPADES, faceUp = true)
    val card7SFU = Card(6, Suits.SPADES, faceUp = true)
    val card8SFU = Card(7, Suits.SPADES, faceUp = true)
    val card9SFU = Card(8, Suits.SPADES, faceUp = true)
    val card10SFU = Card(9, Suits.SPADES, faceUp = true)
    val card11SFU = Card(10, Suits.SPADES, faceUp = true)
    val card12SFU = Card(11, Suits.SPADES, faceUp = true)
    val card13SFU = Card(12, Suits.SPADES, faceUp = true)

    val deck = mutableListOf(
        card1C, card2C, card3C, card4C, card5C, card6C, card7C, card8C, card9C, card10C, card11C, card12C, card13C,
        card1D, card2D, card3D, card4D, card5D, card6D, card7D, card8D, card9D, card10D, card11D, card12D, card13D,
        card1H, card2H, card3H, card4H, card5H, card6H, card7H, card8H, card9H, card10H, card11H, card12H, card13H ,
        card1S, card2S, card3S, card4S, card5S, card6S, card7S, card8S, card9S, card10S, card11S, card12S, card13S,
    )
}